version: "3.7"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=gudangObat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/gudangObatv2
    ports:
      - "8000:8000"
    depends_on:
      - db