version: "3.7"
   
services:
  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=gudangObat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/

  web:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web-django:/usr/src/app
      - ./web-static:/usr/src/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db